Zipcode.create("zip_code"=>"544", "latitude"=>"40.81", "longitude"=>"-73.04", "county"=>"Suffolk County", "country"=>" US", "state"=>"NY", "city"=>"Holtsville", "zipcode_type"=>"UNIQUE")
Zipcode.create("zip_code"=>"601", "latitude"=>"18.16", "longitude"=>"-66.72", "county"=>"Adjuntas", "country"=>" US", "state"=>"PR", "city"=>"Adjuntas", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"602", "latitude"=>"18.38", "longitude"=>"-67.18", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Aguada", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"603", "latitude"=>"18.43", "longitude"=>"-67.15", "county"=>"Aguadilla", "country"=>" US", "state"=>"PR", "city"=>"Aguadilla", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"604", "latitude"=>"18.43", "longitude"=>"-67.15", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Aguadilla", "zipcode_type"=>"PO BOX")
Zipcode.create("zip_code"=>"605", "latitude"=>"18.43", "longitude"=>"-67.15", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Aguadilla", "zipcode_type"=>"PO BOX")
Zipcode.create("zip_code"=>"606", "latitude"=>"18.18", "longitude"=>"-66.98", "county"=>"Maricao", "country"=>" US", "state"=>"PR", "city"=>"Maricao", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"610", "latitude"=>"18.28", "longitude"=>"-67.14", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Anasco", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"611", "latitude"=>"18.28", "longitude"=>"-66.79", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Angeles", "zipcode_type"=>"PO BOX")
Zipcode.create("zip_code"=>"612", "latitude"=>"18.45", "longitude"=>"-66.73", "county"=>"Arecibo", "country"=>" US", "state"=>"PR", "city"=>"Arecibo", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"613", "latitude"=>"18.45", "longitude"=>"-66.73", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Arecibo", "zipcode_type"=>"PO BOX")
Zipcode.create("zip_code"=>"614", "latitude"=>"18.45", "longitude"=>"-66.73", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Arecibo", "zipcode_type"=>"PO BOX")
Zipcode.create("zip_code"=>"616", "latitude"=>"18.4", "longitude"=>"-66.66", "county"=>"Arecibo", "country"=>" US", "state"=>"PR", "city"=>"Bajadero", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"617", "latitude"=>"18.45", "longitude"=>"-66.53", "county"=>"Barceloneta", "country"=>" US", "state"=>"PR", "city"=>"Barceloneta", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"622", "latitude"=>"17.99", "longitude"=>"-67.15", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Boqueron", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"623", "latitude"=>"18.08", "longitude"=>"-67.14", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Cabo Rojo", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"624", "latitude"=>"18.06", "longitude"=>"-66.72", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Penuelas", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"627", "latitude"=>"18.48", "longitude"=>"-66.84", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Camuy", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"631", "latitude"=>"18.19", "longitude"=>"-66.82", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Castaner", "zipcode_type"=>"PO BOX")
Zipcode.create("zip_code"=>"636", "latitude"=>"18.15", "longitude"=>"-67.06", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Rosario", "zipcode_type"=>"PO BOX")
Zipcode.create("zip_code"=>"637", "latitude"=>"18.08", "longitude"=>"-66.96", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Sabana Grande", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"638", "latitude"=>"18.33", "longitude"=>"-66.47", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Ciales", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"641", "latitude"=>"18.27", "longitude"=>"-66.7", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Utuado", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"646", "latitude"=>"18.47", "longitude"=>"-66.27", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Dorado", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"647", "latitude"=>"17.96", "longitude"=>"-66.94", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Ensenada", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"650", "latitude"=>"18.36", "longitude"=>"-66.56", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Florida", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"652", "latitude"=>"18.45", "longitude"=>"-66.6", "county"=>"Arecibo", "country"=>" US", "state"=>"PR", "city"=>"Garrochales", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"653", "latitude"=>"17.97", "longitude"=>"-66.93", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Guanica", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"656", "latitude"=>"18.02", "longitude"=>"-66.79", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Guayanilla", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"659", "latitude"=>"18.48", "longitude"=>"-66.82", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Hatillo", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"660", "latitude"=>"18.14", "longitude"=>"-67.12", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Hormigueros", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"662", "latitude"=>"18.5", "longitude"=>"-67.02", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Isabela", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"664", "latitude"=>"18.22", "longitude"=>"-66.59", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Jayuya", "zipcode_type"=>"STANDARD")
Zipcode.create("zip_code"=>"667", "latitude"=>"18.04", "longitude"=>"-67.06", "county"=>"", "country"=>" US", "state"=>"PR", "city"=>"Lajas", "zipcode_type"=>"STANDARD")
